//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Call.Cloud.Mvc.ServiceAgent {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Agent", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Agent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAgentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fullname {
            get {
                return this.FullnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullnameField, value) != true)) {
                    this.FullnameField = value;
                    this.RaisePropertyChanged("Fullname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAgent {
            get {
                return this.IdAgentField;
            }
            set {
                if ((this.IdAgentField.Equals(value) != true)) {
                    this.IdAgentField = value;
                    this.RaisePropertyChanged("IdAgent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceAgent.AgentIService")]
    public interface AgentIService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgentIService/MostrarAgentes", ReplyAction="http://tempuri.org/AgentIService/MostrarAgentesResponse")]
        Call.Cloud.Mvc.ServiceAgent.Agent[] MostrarAgentes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgentIService/MostrarAgentes", ReplyAction="http://tempuri.org/AgentIService/MostrarAgentesResponse")]
        System.Threading.Tasks.Task<Call.Cloud.Mvc.ServiceAgent.Agent[]> MostrarAgentesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AgentIServiceChannel : Call.Cloud.Mvc.ServiceAgent.AgentIService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgentIServiceClient : System.ServiceModel.ClientBase<Call.Cloud.Mvc.ServiceAgent.AgentIService>, Call.Cloud.Mvc.ServiceAgent.AgentIService {
        
        public AgentIServiceClient() {
        }
        
        public AgentIServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AgentIServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgentIServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgentIServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Call.Cloud.Mvc.ServiceAgent.Agent[] MostrarAgentes() {
            return base.Channel.MostrarAgentes();
        }
        
        public System.Threading.Tasks.Task<Call.Cloud.Mvc.ServiceAgent.Agent[]> MostrarAgentesAsync() {
            return base.Channel.MostrarAgentesAsync();
        }
    }
}
