//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Call.Cloud.Mvc.ServiceBusiness {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="business", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class business : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BusinessKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameBusinesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BusinessKey {
            get {
                return this.BusinessKeyField;
            }
            set {
                if ((this.BusinessKeyField.Equals(value) != true)) {
                    this.BusinessKeyField = value;
                    this.RaisePropertyChanged("BusinessKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameBusines {
            get {
                return this.NameBusinesField;
            }
            set {
                if ((object.ReferenceEquals(this.NameBusinesField, value) != true)) {
                    this.NameBusinesField = value;
                    this.RaisePropertyChanged("NameBusines");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceBusiness.BusinessIService")]
    public interface BusinessIService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BusinessIService/MostrarBusiness", ReplyAction="http://tempuri.org/BusinessIService/MostrarBusinessResponse")]
        Call.Cloud.Mvc.ServiceBusiness.business[] MostrarBusiness();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BusinessIService/MostrarBusiness", ReplyAction="http://tempuri.org/BusinessIService/MostrarBusinessResponse")]
        System.Threading.Tasks.Task<Call.Cloud.Mvc.ServiceBusiness.business[]> MostrarBusinessAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BusinessIServiceChannel : Call.Cloud.Mvc.ServiceBusiness.BusinessIService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BusinessIServiceClient : System.ServiceModel.ClientBase<Call.Cloud.Mvc.ServiceBusiness.BusinessIService>, Call.Cloud.Mvc.ServiceBusiness.BusinessIService {
        
        public BusinessIServiceClient() {
        }
        
        public BusinessIServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BusinessIServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessIServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessIServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Call.Cloud.Mvc.ServiceBusiness.business[] MostrarBusiness() {
            return base.Channel.MostrarBusiness();
        }
        
        public System.Threading.Tasks.Task<Call.Cloud.Mvc.ServiceBusiness.business[]> MostrarBusinessAsync() {
            return base.Channel.MostrarBusinessAsync();
        }
    }
}
